version: "3"
services:
  mlflow:
    restart: always
    image: ghcr.io/mlflow/mlflow:v2.13.0
    command: mlflow server --app-name basic-auth --backend-store-uri sqlite:///.mlflow/mlflow.db --default-artifact-root=.mlflow/mlruns --host 0.0.0.0 --port 5002
    environment:
      MLFLOW_AUTH_CONFIG_PATH: .mlflow/basic_auth.ini
    ports:
      - 5002:5002
    volumes:
      - /home/ubuntu/.mlflow:/.mlflow
